[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc2021"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.4.0"
regex = "^1.5.4"
assert_matches = "^1.5.0"
itertools = "^0.10.3"
priority-queue = "^1.2.1"
typed-arena = "^2.0.1"
